### ISSUE TITLE
[Backend] As a logged in user, I can fetch a survey detail

### ISSUE THREAD

**Issue by chiiida** [llleyelll/ic-surveys-ios#52]
## Why

- Fetch survey question list in order to show on survey question screen.
 
## Acceptance Criteria

- Call API endpoint `/api/v1/surveys/{{surveyId}}`
- After successful request decode the response to object for use later.

**Comment by sleepylee** [comment]
for the title naming I think you can simply call this: 
`[Backend] As a logged in user, I can fetch a survey detail` 

as usually in CRUD, `/resource/:id` usually means that you are fetching for 1 particular record 😁  since we had `surveys` (plural), you can make a ticket relates to the same survey resource by calling it `survey` (singular). 

Using the question inside `survey` or even using the background URL, description, rating options...are up to the integration task. But on this task, we indicate that we will fetch everything about `survey` by a `survey_id`. Does it sound good to you? 😁

**Comment by chiiida** [comment]
@sleepylee It looks better. Thank you so much 🙏
